<?php

use Application\Application\Form\Misc\ConfirmationForm;
use Application\Application\View\Renderer\PhpRenderer;
use Application\Controller\Composante\ComposanteController;
use Application\Controller\Formation\TypeDiplomeController;

/**
 * @see \Application\Controller\Formation\TypeDiplomeController::supprimerAction()
 * @var PhpRenderer $this
 * @var string $title
 * @var ConfirmationForm $form
 */

$this->headTitle($title);
?>

<div class="card border-0">
    <?php if ($title) : ?>
        <h1 class="card-header page-header">
            <?= $title ?>
        </h1>
    <?php endif; ?>
    <div class="card-body">
        <?= $this->confirmation($form) ?>
    </div>
</div>



<script>
    $(function () {
        let body = $("body");
        body.off("<?= TypeDiplomeController::EVENT_SUPPRIMER?>", closeModal)
            .one("<?= TypeDiplomeController::EVENT_SUPPRIMER?>",   closeModal)

        body.off("<?= TypeDiplomeController::EVENT_SUPPRIMER?>", refreshFlashMessage)
            .one("<?= TypeDiplomeController::EVENT_SUPPRIMER?>",   refreshFlashMessage);
    });
</script>