version: '2.1'

services:
  smile-app:
    image: smile-image/php8
    container_name: smile-container
    build:
      context: .
      args:
        PHP_VERSION: 8.0
    env_file:
      - .env
    ports:
     - "8080:80"
     - "8443:443"
    volumes:
     - .:/var/www/html:delegated
    working_dir: /var/www/html

  db:
    image: postgres:13.7
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    ports:
      - 8432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker/db/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
