version: '2.1'
services:
  memcached:
    build:
      context: .
      dockerfile: DockerfileMemcached
    container_name: memcached
    networks:
      - smile-network    

  smile-app:
    build:
      context: .
      dockerfile: DockerfileApp
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: smile-app
    networks:
      - smile-network
    working_dir: /var/www/html/smile
    user: root
    entrypoint: ["/bin/sh", "-c"]
    command:
    - | 
        php-fpm
    volumes:
      - ./src:/var/www/html/smile/
      - ./src/vendor:/var/www/html/smile/vendor
      - ./.env:/var/www/html/smile/.env
      #- ./deploy_configuration/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./deploy_configuration/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./deploy_configuration/php/90-dev.ini:/usr/local/etc/php/php.ini
      - ./deploy_configuration/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./deploy_configuration/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  smile-service:
    container_name: smile-service
    build:
      context: .
      dockerfile: DockerfileApacheService
    working_dir: /var/www/html/smile/public
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        a2dismod shib &&
        a2disconf shib &&
        apachectl configtest &&
        /usr/bin/supervisord -n -c /supervisord.conf
    environment:
      SMILE_INSTANCE_URL: localhost
      SMILE_CORE_POD_NAME: smile-app
      MODE: development
    networks:
      - smile-network
    volumes:
      - ./cache:/var/www/html/smile/cache
      - ./src:/var/www/html/smile
      - ./deploy_configuration/apache/supervisor-localhost.conf:/supervisord.conf
      - ./deploy_configuration/apache/smile-localhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./deploy_configuration/apache/smile-localhost.conf:/etc/apache2/sites-available/default-ssl.conf
    ports:
      - 8080:80
      - 8443:443


  smile-database:
    build:
      context: .
      dockerfile: DockerfileDatabase
    container_name: smile-database
    restart: always
    networks:
      - smile-network
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PSWD:-admin}
      POSTGRES_DB: ${DB_NAME:-demo}
      PGDATA: /smile-database-data
    ports:
      - 5432:5432
    volumes:
      - ./smile-database-data:/smile-database-data
      - ./deploy_configuration/db/:/scripts_to_init/
      - ./deploy_configuration/run_sql.sh:/docker-entrypoint-initdb.d/run_sql.sh

volumes:
  deploy_configuration:
  smile-database-data:
  src:
networks:
  smile-network:
    driver: bridge