<?php

use Application\Entity\Document;
use Application\Entity\Inscription;
use UnicaenApp\Filter\BytesFormatter;

/**
 * @var Document[] $documents
 * @var Inscription $inscription
 * @var \Application\Entity\Mobilite $mobilite
 */

$mobilite = $inscription->getMobilite();
if($mobilite):
    $typeDocsToAdd = $mobilite->getTypedocuments();

    foreach ($documents as $doc) {
        foreach ($typeDocsToAdd as $key => $td) {
            if($doc->getTypedocument()) {
                if($doc->getTypedocument()->getId() === $td->getId()) {
                    $typeDocsToAdd->remove($key);
                }
            }
        }
    }

?>
<table class="table">
    <thead>
    <tr>
        <th>Type</th>
        <th>Name</th>
        <th>File size</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php

    /**
     * @see \Application\Controller\Dashboard\DashboardController::removeDocumentAction()
     */

    if($documents): ?>
        <?php foreach ($documents as $doc): ?>
            <?php
                if($doc->getFichier()->getNature()->getLibelle() === 'Documents') {
                    if($doc->getTypedocument()) {
                        if($doc->getTypedocument()->getLibelle() !== 'Documents') {
                            $typeDoc = $doc->getTypedocument()->getLibelle();
                        }else {
                            $typeDoc = 'Documents';
                        }
                    }else {
                        $typeDoc = 'Documents';
                    }
                }else {
                    $typeDoc = $doc->getFichier()->getNature()->getLibelle();
                }
            ?>
            <tr>
                <td><?= $typeDoc ?></td>
                <td><?= $doc->getFichier()->getNomOriginal() ?></td>
                <td><?= (new BytesFormatter())->filter($doc->getFichier()->getTaille()) ?></td>
                <td>
                    <a target="_blank" href="<?= $this->url('download-fichier', ['fichier' => $doc->getFichier()->getId()]) ?>"><i class="fa-solid fa-eye"></i></a>
                    <a href="<?= $this->url('dashboard/removeDocument').'/'.$doc->getFichier()->getNomOriginal() ?>"><i class="fa-solid fa-trash" style="color: red;"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php foreach($typeDocsToAdd as $td): ?>
        <tr>
            <td><?= $td->getLibelle() ?></td>
            <td>
            </td>
            <td></td>
            <td>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php
  endif;
  ?>