<p><?= $this->translate('Faculty');?>:
    <?= ($this->mainComponent) ? $this->mainComponent->getGroupeLibelle() : '' ?></p>
<table id="tableChoices" class="table table-striped">
    <thead>
    <tr>
        <th scope="col"><?= $this->translate('Name')?></th>
        <th scope="col"><?= $this->translate('ECTS')?></th>
        <th scope="col"><?= $this->translate('Main')?></th>
    </tr>
    </thead>
    <tbody id="choices">
    <?php
    $nEcts = 0;
    foreach ($this->courses as $c) :
        $nEcts += $c->getEcts();
        ?>
        <tr>
            <td><?= $c->getLibelle() ?></td>
            <td><?= $c->getEcts() ?></td>
            <td><?php
                if($c->getFormation()->getComposante()->getId() === $this->mainComponent->getId())
                {
                    echo '<i class="fa-solid fa-check"></i>';
                }
                ?></td>
        </tr>
    <?php endforeach; ?>
        <tr>
            <td></td>
            <td>Total : <?= $nEcts ?></td>
            <td></td>
        </tr>
    </tbody>
</table>
