<div class="row">
    <div class="col">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url());

        $fieldset = $form->get('inscriptionfieldset');

        $firstname = $fieldset->get('firstname');
        $firstname->setAttribute('class', 'form-control');
        $firstname->setAttribute('placeholder', 'Prénom');

        $lastname = $fieldset->get('lastname');
        $lastname->setAttribute('class', 'form-control');
        $lastname->setAttribute('placeholder', 'Nom');

        $birthDate = $fieldset->get('birthDate');
        $birthDate->setAttribute('class', 'form-control');
        $birthDate->setAttribute('placeholder', 'Nom');

        $email = $fieldset->get('email');
        $email->setAttribute('class', 'form-control');
        $email->setAttribute('placeholder', 'Nom');

        $address = $fieldset->get('address');
        $address->setAttribute('class', 'form-control');
        $address->setAttribute('placeholder', 'Nom');

        $submit = $fieldset->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');

        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <fieldset>
            <div class="row">
                <div class="col-md-6">
                    <?= $this->formLabel($firstname); ?>
                    <?= $this->formElement($firstname); ?>
                    <?= $this->formElementErrors()->render($firstname, ['class' => 'help-block']); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formLabel($lastname); ?>
                    <?= $this->formElement($lastname); ?>
                    <?= $this->formElementErrors()->render($lastname, ['class' => 'help-block']); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formLabel($birthDate); ?>
                    <?= $this->formElement($birthDate); ?>
                    <?= $this->formElementErrors()->render($birthDate, ['class' => 'help-block']); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formLabel($email); ?>
                    <?= $this->formElement($email); ?>
                    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']); ?>
                </div>
                <div class="col-md-6">
                    <?= $this->formLabel($address); ?>
                    <?= $this->formElement($address); ?>
                    <?= $this->formElementErrors()->render($address, ['class' => 'help-block']); ?>
                </div>
            </div>
        </fieldset>
        <?php
        echo $this->formSubmit($submit);
        echo $this->formHidden($fieldset->get('id'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>