<?php

use Application\Application\Form\Composante\ComposanteForm;
use Application\Application\View\Helper\Composante\ComposanteViewHelper;
use Application\Application\View\Renderer\PhpRenderer;
use Application\Controller\Composante\ComposanteController;

/**
 * @see ComposanteController::modifierAction()
 * @var PhpRenderer $this
 * @var string $title
 * @var ComposanteForm $form
 */

$this->headTitle($title);

/** @var ComposanteViewHelper $vh */
$vh = $this->composante();
?>

<?= $vh->renderForm($form) ?>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= ComposanteController::EVENT_MODIFIER?>", closeModal)
            .one("<?= ComposanteController::EVENT_MODIFIER?>",   closeModal)

        body.off("<?= ComposanteController::EVENT_MODIFIER?>", refreshFlashMessage)
            .one("<?= ComposanteController::EVENT_MODIFIER?>",   refreshFlashMessage);
    });
</script>