<?php
use Application\Application\View\Helper\Formation\TypeDiplomeViewHelper;
use Application\Application\View\Renderer\PhpRenderer;
use  Application\Entity\TypeDiplome;

/**
 * @see \Application\Controller\Formation\TypeDiplomeController::getActionsMenuAction()
 * @var PhpRenderer $this
 * @var TypeDiplome $typeDiplome
 */
/** @var TypeDiplomeViewHelper $vh */

$vh = $this->typeDiplome($typeDiplome);

$actions = [];
$actions[] = $vh->renderLienModifier();
$actions[] = $vh->renderLienSupprimer();
$actions = array_filter($actions, function($link){
    return (isset($link) && $link != null);
});
?>

<div class="collapsable-actions" data-auto-toggle="true">
    <?php foreach ($actions as $link) : ?>
        <?=$link?>
    <?php endforeach; ?>
    <?php if(sizeof($actions) == 0) :?>
        <span class="text-muted mx-3">Aucune action disponible</span>
    <?php endif; ?>
</div>
