<?php

use Application\Application\Form\Misc\ConfirmationForm;
use Application\Application\View\Helper\Composante\ComposanteViewHelper;
use Application\Application\View\Helper\Formation\TypeFormationViewHelper;
use Application\Application\View\Renderer\PhpRenderer;
use Application\Controller\Composante\ComposanteController;
use  Application\Entity\Composante;
use  Application\Entity\TypeFormation;
use UnicaenApp\View\Helper\Messenger;

/**
 * @see \Application\Controller\Formation\TypeFormationController::getActionsMenuAction()
 * @var PhpRenderer $this
 * @var TypeFormation $typeFormation
 */
/** @var TypeFormationViewHelper $vh */

$vh = $this->typeFormation($typeFormation);

$actions = [];
$actions[] = $vh->renderLienModifier();
$actions[] = $vh->renderLienSupprimer();
$actions = array_filter($actions, function($link){
    return (isset($link) && $link != null);
});
?>

<div class="collapsable-actions" data-auto-toggle="true">
    <?php foreach ($actions as $link) : ?>
        <?=$link?>
    <?php endforeach; ?>
    <?php if(sizeof($actions) == 0) :?>
        <span class="text-muted mx-3">Aucune action disponible</span>
    <?php endif; ?>
</div>
