<?php

/**
 * @see \Application\Controller\Dashboard\DashboardController::indexAction()
 * @var Inscription $inscription
 * @var \UnicaenUtilisateur\Entity\Db\User $user
 * @var \Application\Entity\Step $step
 * @var \Application\Entity\Step[] $steps
 * @var \Application\Entity\Stepmessage $stepMsg
 * @var \Application\Entity\Step $stepCourses
 * @var \Application\Entity\Step $stepRegistration
 * @var \Application\Entity\Step $stepApprovalStudent
 * @var \Application\Entity\Document[] $documents
 * @var \Application\Entity\Mobilite $mobilite
 */

use Application\Entity\Inscription;
use UnicaenApp\Filter\BytesFormatter;

$inscription = $this->inscription;
$user = $this->user;
$messages = $this->messages;
$step = $inscription->getStep();
$steps = $this->steps;
$stepMsg = $this->stepMsg;
$stepCourses = $this->stepCourses;
$stepRegistration = $this->stepRegistration;
$stepApprovalStudent = $this->stepApprovalStudent;
$documents = $this->documents;
$mobilite = $inscription->getMobilite();

//echo $step->getOrder().' '.$stepCourses->getCode();
$isBeforeCourses = ($step->getOrder() < $stepCourses->getOrder()) ? 1 : 0;
$isAfterCourses = ($step->getOrder() > $stepCourses->getOrder()) ? 1 : 0;
$isAtRegistration = ($step->getOrder() === ($stepRegistration->getOrder()-1)) ? 1 : 0;
$isAtApprovalStudent = ($step->getOrder() === ($stepApprovalStudent->getOrder())) ? 1 : 0;

?>
<div class="container" id="dashboard">
    <div class="row">
        <div class="col headTitle">
            <h2>MY SPACE</h2>
        </div>
    </div>
    <?=
    $this->partial('application/index/partials/registration.phtml', ['period' => $this->period])
    ?>
    <?php
    if($inscription->getStatus() != Inscription::STATUS_ABANDON[0]) :
        if($stepMsg):
            ?>
            <div class="row">
                <div class="col text-center">
                    <div class="alert alert-warning" role="alert">
                        <p>
                            Your registration has been returned to previous step with the following message :<br>
                            <b><?= $stepMsg->getLibelle() ?></b>
                        </p>
                    </div>
                </div>
            </div>
        <?php
        endif;
        ?>

        <div class="row">
            <div class="col-4 informations">
                <div class="row text-center ">
                    <div class="col">
                        <a class="btn btn-info m-3" href="<?= $this->url('inscription/information') ?>">My registration</a>
                    </div>
                    <?php echo $this->partial('partials/step.phtml', ['steps' => $steps, 'step' => $step]) ?>
                </div>
                <div class="row">
                    <?= $this->render('application/index/partials/messagerie.phtml', [
                        'messages' => $messages,
                        'user' => $user,
                        'inscription' => $inscription
                    ]); ?>
                </div>
                <div class="row">
                    <div class="col mb-2 text-center">
                        <hr>
                        <a href="" class="btn btn-danger " data-bs-toggle="modal" data-bs-target="#abandonModal">
                            <?= $this->translate('Abandonner mon inscription') ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-8 text-center inscriptionStatus">
                <?php
                if($isAtApprovalStudent):
                    ?>
                    <div class="row">
                        <div class="col text-center">
                            <?php
                            /**
                             * @see Application\Controller\Dashboard\DashboardController::generatePdfAction()
                             */
                            ?>
                            <p class="alert alert-info">
                                Validate my information and generate my OLA<br><a href="<?= $this->url('dashboard/generatePdf') ?>" class="btn btn-success mt-1">Validate</a>
                            </p>
                        </div>
                    </div>
                <?php
                endif;
                ?>
                <div class="row">
                    <div class="col">
                        <h3 class="titleBlue">Courses - <?php if($mobilite) { echo $mobilite->getLibelle(); } ?></h3>
                        <?php if(!$isBeforeCourses): ?>
                            <?= $this->render('application/index/partials/tableCourses.phtml', ['role' => $this->role,'courses' => $this->courses, 'mainComponent' => $this->mainComponent, 'inscription' => $this->inscription]); ?>
                            <?php
                                if(!$isAfterCourses) :
                            ?>
                                <div class="row">
                                    <div class="col-md-3">
                                        <a class="btn btn-info left" href="dashboard/courses"><?= $this->translate('Select my courses'); ?></a>
                                    </div>
                                    <div class="col-6">
                                        <p class="alert alert-info mb-0 p-2 right"><?= $this->translate('Validate your courses to proceed to the next step'); ?></p>
                                    </div>
                                    <div class="col-md-3">
                                        <form action="dashboard/validateCourses" method="POST">
                                            <button class="btn btn-success right" type="submit" <?php if($this->courses->isEmpty()) { echo 'disabled'; } ?>> <?= $this->translate('Valid my courses');?></button>
                                        </form>
                                    </div>
                                </div>
                            <?php
                                endif;
                            ?>
                        <?php else: ?>
                            <div class="row">
                                <div class=" col-md-12" style="padding: 20px;">
                                    <p class="alert alert-info"><?= $this->translate('Pending validation, you can only view the courses.');?></p>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>

                </div>
                <hr>
                <div class="row">
                    <div class="col">
                        <h3 class="titleBlue">Documents</h3>

                        <?= $this->render('application/index/partials/documents.phtml'); ?>
                        <a href="<?= $this->url('dashboard/uploadFichier') ?>" class="btn btn-info ajax-modal right mb-2" data-event="modification">Upload</a>

                    </div>
                </div>
            </div>

        </div>
    <?php else: ?>
        <div class="row">
            <div class="col text-center">
                <div class="alert alert-danger" role="alert">
                    <p>
                        <?= $this->translate('Your registration has been abandoned. ') ?>
                    </p>
                </div>
            </div>
        </div>
    <?php endif; ?>
    </div>
    <div class="modal vanilla fade" id="abandonModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Abandon</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p class="alert alert-danger">
                        <?= $this->translate("L'abandon est définitif, êtes-vous sûr ?") ?>
                    </p>
                </div>
                <div class="modal-footer">
                    <form action="<?= $this->url('dashboard/abandon') ?>" method="POST">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                        <input type="submit" class="btn btn-danger" value="<?= $this->translate('Abandonner') ?>"/>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    </script>
