<?php

/**
 * @var \UnicaenUtilisateur\Entity\Db\User $user
 */
$user = $this->user;
?>
<style>
.container {
    display: flex;
}
.header h1{
    text-align: center;
}
.body {
    width: 100%;
}
.flexDiv-2 {
    width: 50%;
}
</style>
<div class='container'>
    <div class="header">
        <h1>CONTRAT D'ETUDE</h1>
    </div>
    <div class="body">
        <div class="flexDiv-2">
            <b>Etudiant :</b>
            Nom, Prénom
            Date de naissance
            Nationalité
            Genre
            ESI
            Cycle d'études (EQF)
            Code ISCED (discipline)
            Discipline
        </div>

        <div>test2</div>
        <div>test3</div>
    </div>
    <div class="footer">

    </div>
</div>